config/routes.rb
Rails.application.routes.draw do

  get 'home/index'
  resources :articles

  get 'articles/index'
  get 'articles/new'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      flash[:success] = "Vous avez crée l'article #{@article.title}."
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      flash[:success] = "Vous avez modifier l'article #{@article.title}"
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private
  def article_params
    params.require(:article).permit(:title, :subtitle, :content)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title, :class => 'input'%>
  </p>
  <br>
  <p>
    <%= form.label :subtitle %><br>
    <%= form.text_field :subtitle, :class => 'input'%>
  </p>
  <br>
  <p>
    <%= form.label :content %><br>
    <%= form.text_area :content, :class => 'textarea' %>
  </p>
  <br>
  <p>
    <%= form.submit :valider, :class => 'button is-primary' %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1 class="title">Modifier un article </h1>

<%= render 'articles/form' %>

app/views/articles/index.html.erb
<div class="section">
  <% @articles.each do |article| %>
    <div class="card">
      <header class="card-header">
        <p class="card-header-title">
          <%= article.title %>
        </p>

        <a href="#" class="card-header-icon" aria-label="more options">
        <span class="icon">
          <i class="fas fa-angle-down" aria-hidden="true"></i>
        </span>
        </a>
      </header>
      <div class="card-content">
        <p><%= article.subtitle %></p>
        <div class="content">
          <%= article.content %>
          <br>
          <time datetime="2016-1-1">11:09 PM - 1 Jan 2016</time>
        </div>
      </div>
      <footer class="card-footer">
        <p class="card-footer-item"><%= link_to 'Show', article_path(article) %></p>
        <p class="card-footer-item"><%= link_to 'Edit', edit_article_path(article) %></p>
        <p class="card-footer-item"><%= link_to 'Destroy', article_path(article), method: :delete, data: { confirm: 'Are you sure?' } %></p>
      </footer>
    </div>
  <% end %>
</div>

app/views/articles/new.html.erb
<div class="section">

<h1 class="title">Ajouter un article</h1>

<%= render 'articles/form' %>
</div>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.content %>
</p>

<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyStarterApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%=render 'layouts/nav' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>